# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_song_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='media_file',
            field=models.FileField(default='File is not avalible', upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default='File is not avalible', upload_to=''),
        ),
    ]
