# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20170217_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='media_file',
            new_name='file',
        ),
    ]
